### ISSUE TITLE
Unrecognized option 'referer'.

### ISSUE THREAD

**Issue by Burden-xy** [bililive-go/bililive-go#431]
### 程序版本

0.7.8

### 程序 log

time="2023-03-27 23:13:22" level=debug msg="Start ParseLiveStream(https://stream-jilin-cu-139-215-238-30.edgesrv.com:443/live/5092355rcztyuX8d.flv?wsAuth=655e174a3c212a511dc542a34a236daf&token=web-h5-0-5092355-445da17a22c3b8ecebee3b7c77e32bd787ba2fa06579b14d&logo=0&expire=0&did=31dcc9ecee184e2d9ec35de007eb025e&pt=2&st=0&vhost=play1&origin=tct&mix=0&isp=scdncujilccidc, 斗鱼/二呆啾/[2023-03-27 23-13-22][二呆啾][休息日哦~记得送荧光棒棒].flv)" host="二呆啾" room="休息日哦~记得送荧光棒棒"
ffmpeg version 2.8.15 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 4.8.5 (GCC) 20150623 (Red Hat 4.8.5-36)
  configuration: --prefix=/usr --bindir=/usr/bin --datadir=/usr/share/ffmpeg --incdir=/usr/include/ffmpeg --libdir=/usr/lib64 --mandir=/usr/share/man --arch=x86_64 --optflags='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic' --extra-ldflags='-Wl,-z,relro ' --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-version3 --enable-bzlib --disable-crystalhd --enable-gnutls --enable-ladspa --enable-libass --enable-libcdio --enable-libdc1394 --enable-libfdk-aac --enable-nonfree --disable-indev=jack --enable-libfreetype --enable-libgsm --enable-libmp3lame --enable-openal --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libvorbis --enable-libv4l2 --enable-libx264 --enable-libx265 --enable-libxvid --enable-x11grab --enable-avfilter --enable-avresample --enable-postproc --enable-pthreads --disable-static --enable-shared --enable-gpl --disable-debug --disable-stripping --shlibdir=/usr/lib64 --enable-runtime-cpudetect
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
Unrecognized option 'referer'.
Error splitting the argument list: Option not found

**Comment by kira1928** [comment]
你的 log 显示 ffmpeg 版本是 2.8.15，我们一般用的是5.1.2，应该是你的环境里的 ffmpeg 过于老旧了吧。
