### ISSUE TITLE
关于下载的ffmpeg或者parser能否参考其他开源录制的下载流方式

### ISSUE THREAD

**Issue by longjiank** [bililive-go/bililive-go#454]
### 新功能

比如录播姬和biliup的下载方式
感觉现在分段太多了，cdn问题和parser问题，虽然能后期合成分段，但还是很麻烦

**Comment by kira1928** [comment]
录播姬类似 parser 的思路，不过它的 parser 做了很长时间的优化，可以解决大部分常见问题，包括录制结束后修复flv文件头让视频可以拖动进度条等等。

biliup我尝试过，当时录制非常不稳定，几乎无法成功录制任何内容，后来就放弃了。我当时试用了好几个同类产品，最后确定了长期使用b站录播姬和现在这个bililive-go项目的方案。

我们的 parser 还处于一个刚好能跑的功能非常基础的状态，所以有各种问题。他唯一的优点就是能解决主播pk时直播分辨率变化问题。ffmpeg录这个会花屏，parser录可以分段。

参考录播姬的问题在于它修复各种问题的代码被组织成了一个精密巧妙但可读性很低的结构，要花大量精力才能进入状态去学习和理解它。与此同时，就算学会了修复了 parser，对我个人的使用体验也没有任何提升，毕竟我不录会 pk 的主播，所以我一直用的 ffmpeg。这就让我很没有动力去聚集这大量的精力去看代码。

我试过强迫自己去做那些对我没有直接帮助的修 bug 之类的工作，下场是我的开源热情被迅速消耗殆尽。之后几个月里我都几乎没有再为这个项目贡献过任何代码了。
现在我好不容易重新开始写信功能了，我希望以维护我个人的开发热情为第一优先，只写一些我感兴趣的部分。其他的 issue 就靠别人发 PR 来修复吧。
或者等项目原作者重新出山。他今年在准备考研，也许明年开始会有时间重新接手项目维护。

**Comment by kira1928** [comment]
你用flv parser录下来之后在config里设置自动转mp4的话，转换后的视频可以正常上传吗？
flv parser 肯定是有问题的，但是同时修复和开发难度也比较大，一直没人有兴趣修理它。
